### ISSUE TITLE
Text double vision when selected

### ISSUE THREAD

**Issue by bluishwu** [ddryo/Highlighting-Code-Block#24]
The problem is as shown in the picture below:
![image](https://github.com/ddryo/Highlighting-Code-Block/assets/20926845/8ffd207f-6c2d-44bf-886a-d7e2303a6998)
1.Appears in the "Blocksy" theme; Normal in other themes(e.g. "Kadence")
2.Cord coloring (front side) in "Dark" shows up fine, but only in "Light" mode bad.
Your help is appreciated!

**Comment by ddryo** [comment]
This is often caused by Blocksy changing the color of selected text using the following CSS:

```
body ::selection {
    color: var(--theme-selection-text-color);
    background-color: var(--theme-selection-background-color)
}
```

**Comment by bluishwu** [comment]
> This is often caused by Blocksy changing the color of selected text using the following CSS:
> 
> ```
> body ::selection {
>     color: var(--theme-selection-text-color);
>     background-color: var(--theme-selection-background-color)
> }
> ```

Thank you so much, good day!
